version: '3.7'
services:
  server:
    container_name: 104-data-crawl-to-db-script
    restart: unless-stopped
    build: 
      context: .
      dockerfile: dockerfile
      args:
        - MONGO_URL=${MONGO_URL:-NOT_EXIST}
    network_mode: bridge
    env_file:
      - .env
    environment: 
      - MONGO_URL=${MONGO_URL:-NOT_EXIST}