name: Craw 104 everyday
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '* * 1 * *'
jobs:
  crawl_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create-env
        run: |
          touch .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          export MONGO_URL = ${{ secrets.MONGO_URL }}

      - name: build-image
        run: docker compose up 